### ISSUE TITLE
Use Multidev when possible

### ISSUE THREAD

**Issue by davidstrauss** [uberhacker/mcu#1]
If a site has Multidev available, prefer creating an environment there for the change so there's no need to back out a broken update from master/dev.

**Comment by uberhacker** [comment]
@davidstrauss: Thank you.  I'll see if I can come up with a solution.  Does Pantheon offer free hosting for this kind of work? ;)

**Comment by uberhacker** [comment]
@davidstrauss: I have committed changes which add the ability to create multidev environments to test contrib updates as requested.  Please check it out when you get a chance and let me know if this works as you expected.
Thanks

**Comment by uberhacker** [comment]
The default environment is mcu.  The dev environment can be targeted instead with <code>--env=dev</code>.
